version: 2

sources:
  - name: jaffle_shop
    database: DBT_DATABASE
    schema: DBT_AJHA
    tables:
      - name: customers
        description: "One record per customer."
      - name: orders
        description: "One record per order. Includes canceled and deleted orders."
